apiVersion: v1
kind: ServiceAccount
metadata:
  name: volume-decorator
  namespace: kube-system

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: volume-decorator-role
rules:
  - apiGroups: ["storage.tkestack.io"]
    resources: ["persistentvolumeclaimruntimes"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: ["apps"]
    resources: ["replicasets", "deployments", "daemonsets", "statefulsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["tkestack.io"]
    resources: ["tapps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["validatingwebhookconfigurations"]
    verbs: ["get", "list", "create", "update"]
  # leader elections
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "update", "create", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: volume-decorator-role-binding
subjects:
  - kind: ServiceAccount
    name: volume-decorator
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: volume-decorator-role
  apiGroup: rbac.authorization.k8s.io
